name: Benchmark the default branch

on:
  push:
    branches:
      - "master"

jobs:
  beenchmark:
    name: Run Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Upload the results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_results
          path: benchmark.json
