name: Release

# manually triggered workflow
on: workflow_dispatch

jobs:
    release_image:
        name: Release docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Docker Meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: pedrozc90/dummy
                  tags: |
                      type=semver,pattern={{version}}

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Build and Push
            #   uses: docker/build-push-action@v2
            #   with:
            #     context: .
            #     push: ${{ github.event_name == 'release' }}
            #     tags: ${{ steps.meta.outputs.tags }}
            #     labels: ${{ steps.meta.outputs.labels }}
