name: Manual Job

on:  [ workflow_dispatch ]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Repository Files
        run: ls -alh ${{ github.workspace }}
      
      - name: Hello world action step
        uses: ./.github/actions/demo # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: "Pedro"

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
