name: Manual Job

on:  [ workflow_dispatch ]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Repository Files
        run: ls -alh ${{ github.workspace }}
      
      - name: Greet
        id: greet
        uses: .github/actions/demo
        with:
          who-to-greet: "Pedro"
